## Connection Details ##
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springBoot
    username: root
    password: root
## ORM Details ##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 12
      max-lifetime: 1200000
      minimum-idle: 5
      idle-timeout: 300000
      auto-commit: true
      